defaults: &defaults
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 10
  username: arjieng

development:
  <<: *defaults
  database: joans

test:
  <<: *defaults
  database: joans

staging:
  <<: *defaults
  database: joans
  password: 213151315a++

production:
  <<: *defaults
  database: joans
  password: 213151315a++

